[project]
name = "drz-intentslot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adapters>=1.2.0",
    "datasets>=4.0.0",
    "flask~=3.1.0",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
    "waitress~=3.0.2",
]
