import glob
import time
import argparse
import random
import torch
import torch.nn.functional as F
import pandas as pd
import numpy as np

from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, EarlyStoppingCallback
from peft import LoraConfig, TaskType
from trl import SFTTrainer

import sentence_transformers 
from sentence_transformers import SentenceTransformer
from sklearn.metrics import confusion_matrix, f1_score
from collections import defaultdict

import datasets
from datasets import Dataset


def flatten(l):
	return [item for sublist in l for item in sublist]


def read_data(path_to_folder):
	# read the text files with annotations one by one
	data_dict = {"train": {}, "dev": {}, "test": {}} # {"train": {"id": {"utterance": str, "slots": {"slot_type": [(tags_as_str, marked_utterance), ...], ...}}}}

	for data_file in [f for f in glob.glob(path_to_folder+"*") if f.endswith(".csv")]: # 
		file_name = data_file.split("/")[-1].strip()[:-4]
		file_name_spl = file_name.split("_")
		if len(file_name_spl) < 4:
			# not partitioned
			continue
		partition = file_name_spl[-1].strip()
		slot_type = file_name_spl[-2].strip()

		df = pd.read_csv(data_file, header=0)

		ids = df["id"]
		utterances = df["tokens"]
		tags_str = df["tags"]

		for _id, _utt, _tags in zip(ids, utterances, tags_str):
			if not _id in data_dict[partition].keys():
				data_dict[partition][_id] = dict()
				data_dict[partition][_id]["utterance"] = _utt
				data_dict[partition][_id]["slots"] = {}
			if not slot_type in data_dict[partition][_id]["slots"].keys():
				data_dict[partition][_id]["slots"][slot_type] = []
			# make target sequence (to be generated by an LLM)
			toks = _utt.split()
			tags = _tags.split()
			try:
				assert(len(toks) == len(tags))
			except AssertionError:
				continue
			target = []
			prev_label = "O"
			for tok, label in zip(toks, tags):

				if label == "O" and prev_label != "O":
					target.append("**")
				elif label != "O" and prev_label == "O":
					target.append("**")
					
				target.append(tok)
				prev_label = label
			if prev_label != "O":
				target.append("**")

			target = " ".join(target)

			data_dict[partition][_id]["slots"][slot_type].append((_tags, target))

	return data_dict


def get_instances(data):

	utterances = []
	ids = []
	slots = []
	marked_utterances = []
	gold_bio = [] # List of lists of separate tags
	for _id, info_dict in data.items():
		utt = info_dict["utterance"]
		slots_dict = info_dict["slots"]
		for slot, l in slots_dict.items():
			for tpl in l:
				utterances.append(utt)
				ids.append(_id)
				slots.append(slot)
				gold_bio.append([t for t in tpl[0].split() if t != ""])
				marked_utterances.append(tpl[1])

	return utterances, ids, slots, gold_bio, marked_utterances


def marked_utterance_to_bio(marked_utterance):
	bio_list = []
	marked_utterance_spl = marked_utterance.strip().split()
	curr_tag = "O"
	for token in marked_utterance_spl:
		if token == "**" and curr_tag == "O":
			curr_tag = "B"
		elif token == "**" and curr_tag != "O":
			curr_tag = "O"
		elif curr_tag == "B":
			bio_list.append(curr_tag)
			curr_tag = "I"
		else:
			bio_list.append(curr_tag)
	try:
		utterance = marked_utterance.replace("**", "")
		toks = [t for t in utterance.split() if t != ""]
		assert(len(toks) == len(bio_list))
	except AssertionError:
		print("AssertionError!!!")
		print(marked_utterance.split())
		print(toks)
		print(bio_list)
		print("*****")
	return bio_list


def preprocess_dataset_with_eos(eos_token, dataset):
	def preprocess_function(examples):
		system = "You are a helpful AI assistant for information extraction."
		instruction = "You are given a radio talk utterance in German and a slot type also in German. There are 5 possible slot types:\n"+\
					"Einheit: a person, a group of people performing a task or an action\n"+\
					"Auftrag: an action or a task someone is to do as part of the mission, as well as a completed or ongoing task (action); often a verb or a noun phrase\n"+\
					"Mittel: a robot, a device, or something else used to accomplish the given task\n"+\
					"Ziel: a location (a destination) someone is to get to\n"+\
					"Weg: a distance or a path taken by someone to reach the desired destination\n"+\
					"Your task is to mark the suitable slot within the given utterance, depending on the slot type. Use ** symbol to mark "+\
					"the begining and the end of the slot. If a suitable slot does not exist, reproduce the given utterance without any markers. "+\
					"Do not give explanations or reasoning. Do not remove any tokens from the sentence.\n"

		curr_utterances = examples["utterance"]
		curr_slots = examples["slot"]
		curr_marked_utterances = examples["marked_utterance"]

		chats = []
		for curr_utterance, curr_slot, curr_marked_utterance in zip(curr_utterances, curr_slots, curr_marked_utterances):
			text = "Utterance: " + curr_utterance + "\n"
			slot = "Slot: " + curr_slot + "\nMarked slots: "
			chat = [
				{"role": "system", "content": system},
				{"role": "user", "content": instruction + text + slot},
				{"role": "assistant", "content": curr_marked_utterance}, # + tokenizer.eos_token
			]
			chats.append(chat)

		return {"messages": chats}

	dataset_preprocessed = dataset.map(preprocess_function, batched=True, remove_columns=dataset.column_names)
	return dataset_preprocessed

# Structures the dataset into prompt-expected output pairs.
def formatting_function(examples):
	return tokenizer.apply_chat_template(examples["messages"], tokenize=False, add_generation_prompt=False)


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument(
		"--model_name",
		default="Alibaba-NLP/gte-multilingual-base",
		help="Model to calculate embedding similarity.",
	)
	parser.add_argument(
		"--gen_model_name",
		#default="JunHowie/Qwen3-32B-GPTQ-Int8",
		default="Qwen/Qwen3-32B",
		#default="Qwen/Qwen3-14B",
		#default="Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8",
		help="LLM to identify slots.",
	)
	parser.add_argument(
		"--data_path",
		default="./neg_samples_csv/",
		help="Path to the data.",
	)
	
	args = parser.parse_args()

	model_name = args.model_name
	gen_model_name = args.gen_model_name
	data_path = args.data_path

	random.seed(12)

	# we will either use bf16 (if available), or fp32
	# we won't use fp16, as it may lead to Less numerical stability, and may require loss scaling in training

	if torch.cuda.is_bf16_supported():
		dtype = torch.bfloat16
		bf16 = True
	else:
		dtype = torch.float32
		bf16 = False

	model = AutoModelForCausalLM.from_pretrained(gen_model_name, device_map="auto", torch_dtype=dtype)
	tokenizer = AutoTokenizer.from_pretrained(gen_model_name)

	#for name, module in model.named_modules():
	#	print(name)

	# make PEFT config to use with LoRA
	peft_config = LoraConfig(
		task_type="CAUSAL_LM", 
		inference_mode=False, 
		r=16, 
		lora_alpha=32, 
		lora_dropout=0.05,
		target_modules=[
			"q_proj",
			"k_proj",
			"v_proj",
			"o_proj",
			"gate_proj",
			"up_proj",
			"down_proj",
		],
	)

	# data
	dataset = read_data(data_path) # dict: {"train": {"id": {"utterance": str, "slots": {"slot_type": [(tags_as_str, marked_utterance), ...], ...}}}}
	train_data = dataset["train"]
	dev_data = dataset["dev"]
	train_utterances, train_ids, train_slots, train_gold_bio, train_marked_utterances = get_instances(train_data)
	dev_utterances, dev_ids, dev_slots, dev_gold_bio, dev_marked_utterances = get_instances(dev_data)
	dataset_train = Dataset.from_dict({"utterance": train_utterances, "id": train_ids, "slot": train_slots, "marked_utterance": train_marked_utterances})
	dataset_dev = Dataset.from_dict({"utterance": dev_utterances, "id": dev_ids, "slot": dev_slots, "marked_utterance": dev_marked_utterances})
	dataset_train = preprocess_dataset_with_eos(tokenizer, dataset_train)
	dataset_dev = preprocess_dataset_with_eos(tokenizer, dataset_dev)
	print(dataset_train)
	print(dataset_dev)

	training_arguments = TrainingArguments(
		output_dir="./"+gen_model_name+"-lora-adapter",
		do_train=True,
		per_device_train_batch_size=1,
		per_device_eval_batch_size=1,
		gradient_accumulation_steps=16,
		num_train_epochs=6,
		eval_strategy="steps",
		eval_steps=10,
		logging_steps=10,
		warmup_steps=5, # overwrites warmup_ratio
		logging_strategy="steps",
		learning_rate=2e-4, # 2e-4
		fp16=False,
		bf16=bf16,
		save_strategy="steps",
		save_steps=10,
		load_best_model_at_end=True,
		metric_for_best_model="eval_loss",
		save_total_limit=1,
		overwrite_output_dir=True,
	)

	trainer = SFTTrainer(
		model=model,
		train_dataset=dataset_train,
		eval_dataset=dataset_dev,
		peft_config=peft_config,
		max_seq_length=256,
		tokenizer=tokenizer,
		args=training_arguments,
		callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
		formatting_func=formatting_function,
	)

	trainer.train()
	trainer.model.save_pretrained("./"+gen_model_name+"-lora-adapter")