import glob
import time
import argparse
import random
import torch
import torch.nn.functional as F
import pandas as pd
import numpy as np

from transformers import AutoModel, AutoTokenizer
from vllm import LLM, SamplingParams

import sentence_transformers 
from sentence_transformers import SentenceTransformer
from sklearn.metrics import confusion_matrix, f1_score
from collections import defaultdict


def flatten(l):
	return [item for sublist in l for item in sublist]


def read_data(path_to_folder):
	# read the text files with annotations one by one
	data_dict = {"train": {}, "dev": {}, "test": {}} # {"train": {"id": {"utterance": str, "slots": {"slot_type": [(tags_as_str, marked_utterance), ...], ...}}}}

	for data_file in [f for f in glob.glob(path_to_folder+"*") if f.endswith(".csv")]: # 
		file_name = data_file.split("/")[-1].strip()[:-4]
		file_name_spl = file_name.split("_")
		if len(file_name_spl) < 4:
			# not partitioned
			continue
		partition = file_name_spl[-1].strip()
		slot_type = file_name_spl[-2].strip()*

		df = pd.read_csv(data_file, header=0)

		ids = df["id"]
		utterances = df["tokens"]
		tags_str = df["tags"]

		for _id, _utt, _tags in zip(ids, utterances, tags_str):
			if not _id in data_dict[partition].keys():
				data_dict[partition][_id] = dict()
				data_dict[partition][_id]["utterance"] = _utt
				data_dict[partition][_id]["slots"] = {}
			if not slot_type in data_dict[partition][_id]["slots"].keys():
				data_dict[partition][_id]["slots"][slot_type] = []
			# make target sequence (to be generated by an LLM)
			toks = _utt.split()
			tags = _tags.split()
			try:
				assert(len(toks) == len(tags))
			except AssertionError:
				continue
			target = []
			prev_label = "O"
			for tok, label in zip(toks, tags):

				if label == "O" and prev_label != "O":
					target.append("**")
				elif label != "O" and prev_label == "O":
					target.append("**")
					
				target.append(tok)
				prev_label = label
			if prev_label != "O":
				target.append("**")

			target = " ".join(target)

			data_dict[partition][_id]["slots"][slot_type].append((_tags, target))

	return data_dict


def get_most_sim(target_utterances, target_ids, source_data, embedder, num_sim=5):

	source_ids, source_utterances = zip(*[(k, v["utterance"]) for k, v in source_data.items()]) # v is {"utterance": str, "slots": {}}
	targets_embs = embedder.encode(target_utterances)
	source_embs = embedder.encode(source_utterances)
	sims = embedder.similarity(targets_embs, source_embs)	
	sims_ids = torch.argsort(sims, dim=-1, descending=True)
	
	# for each target utterance, we want to avoid having the same ones as the most similar ==> we remove them
	target_ids = torch.tensor(target_ids)
	source_ids_sorted = torch.tensor(np.array(source_ids)[np.array(sims_ids.reshape(1, -1).squeeze(0))]).reshape(sims.shape[0], -1)
	mask = source_ids_sorted != target_ids.unsqueeze(1)
	
	# apply mask row-wise, pad where necessary (with 0, which means the index of the most similar example!), then reshape
	source_ids_sorted_clean = [row[mask[i]] if len(row[mask[i]]) == len(row) else F.pad(row[mask[i]], (0, len(row) - len(row[mask[i]]))) for i, row in enumerate(source_ids_sorted)]
	source_ids_sorted_clean = torch.stack(source_ids_sorted_clean, dim=0)
	
	# extract column indices
	source_ids_most_sim = source_ids_sorted_clean[:, :num_sim].tolist() #.reshape(1, -1).squeeze(0)

	return source_ids_most_sim


def get_instances(data):

	utterances = []
	ids = []
	slots = []
	marked_utterances = []
	gold_bio = [] # List of lists of separate tags
	for _id, info_dict in data.items():
		utt = info_dict["utterance"]
		slots_dict = info_dict["slots"]
		for slot, l in slots_dict.items():
			for tpl in l:
				utterances.append(utt)
				ids.append(_id)
				slots.append(slot)
				gold_bio.append([t for t in tpl[0].split() if t != ""])
				marked_utterances.append(tpl[1])

	return utterances, ids, slots, gold_bio, marked_utterances


def marked_utterance_to_bio(marked_utterance):
	bio_list = []
	marked_utterance_spl = marked_utterance.strip().split()
	curr_tag = "O"
	for token in marked_utterance_spl:
		if token == "**" and curr_tag == "O":
			curr_tag = "B"
		elif token == "**" and curr_tag != "O":
			curr_tag = "O"
		elif curr_tag == "B":
			bio_list.append(curr_tag)
			curr_tag = "I"
		else:
			bio_list.append(curr_tag)
	try:
		utterance = marked_utterance.replace("**", "")
		toks = [t for t in utterance.split() if t != ""]
		assert(len(toks) == len(bio_list))
	except AssertionError:
		print("AssertionError!!!")
		print(marked_utterance.split())
		print(toks)
		print(bio_list)
		print("*****")
	return bio_list


def identify_slots(model_name, gen_model_name, data_dict):
	train_data = data_dict["train"]
	test_data = data_dict["test"]
	print("Len train:", len(train_data.keys()))
	print("Len test:", len(test_data.keys()))

	#train_data = dict(random.sample(train_data.items(), 50))
	#test_data = dict(random.sample(test_data.items(), 5))

	# extract gold test data
	test_utterances, test_ids, test_slots, test_gold_bio, test_marked_utterances = get_instances(test_data)
	# for each test utterances, find top N most similar ones (avoiding the same ones)
	embedder = SentenceTransformer(model_name, trust_remote_code=True, truncate_dim=768, device="cuda")
	most_sim_ids = get_most_sim(test_utterances, test_ids, train_data, embedder)

	# Create a sampling params object.
	sampling_params = SamplingParams(
		temperature=0.7, ### thinking 0.6 / no thinking 0.7 (only DeepSeek / Qwen3 relevant)
		top_p=0.8, ### thinking 0.95 / no thinking 0.8 (only DeepSeek / Qwen3 relevant)
		top_k=20, ### thinking 20 / no thinking 20 (only DeepSeek / Qwen3 relevant)
		min_p=0, ### thinking 0 / no thinking 0 (only DeepSeek / Qwen3 relevant)
		max_tokens=128,
	)

	# Create an LLM with prefix caching enabled.
	gen_model = LLM(
		model=gen_model_name,
		enable_prefix_caching=False,
		gpu_memory_utilization=0.9,
		tensor_parallel_size=2, # how many GPUs to be used?
		max_model_len = 4096,
	)

	# make a prompt
	instruction = "You are given a radio talk utterance in German and a slot type. There are 5 possible slot types:\n"+\
					"einheit: a person, a group of people, a robot or a device performing a task or an action\n"+\
					"auftrag: a task someone is to do\n"+\
					"mittel: something that is used to accomplish the task\n"+\
					"ziel: a location (a destination) someone is to get to\n"+\
					"weg: a path taken by someone to reach the desired destination\n"+\
					"Your task is to mark the suitable slot within the given utterance, depending on the slot type. Use ** symbol to mark "+\
					"the begining and the end of the slot. If a suitable slot does not exist, reproduce the given utterance without any markers. "+\
					"Do not give explanations or reasoning. Do not remove any tokens from the sentence. Below are some examples.\n"

	test_pred_bio = []

	batch_size = 2
	test_instances = [] # together with examples
	instance_counter = 0
	generated_texts = []

	for test_utterance, test_id, test_slot, curr_most_sim_ids in zip(test_utterances, test_ids, test_slots, most_sim_ids):
		if instance_counter == batch_size:
			# process full batch
			outputs = gen_model.chat(test_instances, sampling_params, use_tqdm=True, chat_template_kwargs={"enable_thinking": False}, add_generation_prompt=True)
			for k, output in enumerate(outputs):
				generated_text = output.outputs[0].text
				generated_texts.append(generated_text)
				#print(f"Generated text: {generated_text!s}")
				#print("-" * 10)
			# reset batch
			instance_counter = 0
			test_instances = []

		examples = []
		for curr_most_sim_id in curr_most_sim_ids:
			curr_info_dict = train_data[curr_most_sim_id]
			curr_utterance = "Utterance: "+curr_info_dict["utterance"]+"\n"
			curr_slot_type = "Slot: "+test_slot+"\n"
			curr_result = "Marked slots:\n"
			try:
				curr_slots = curr_info_dict["slots"][test_slot]
				curr_result += "\n".join([tpl[1] for tpl in curr_slots])
			except KeyError:
				curr_result += curr_info_dict["utterance"] # no slots
			example = curr_utterance + curr_slot_type + curr_result
			examples.append(example)

		examples = "\n".join(examples)

		test_instance = [{"role": "user", "content": f"{instruction}{examples}\nUtterance: {test_utterance}\nSlot: {test_slot}\nMarked slots:\n"}]
		test_instances.append(test_instance)
		instance_counter += 1

	# in case we still have test instrances:
	if instance_counter != 0:
		outputs = gen_model.chat(test_instances, sampling_params, use_tqdm=True, chat_template_kwargs={"enable_thinking": False}, add_generation_prompt=True)
		for k, output in enumerate(outputs):
			generated_text = output.outputs[0].text
			generated_texts.append(generated_text)
			#print(f"Generated text: {generated_text!s}")
			#print("-" * 10)
		# reset batch
		instance_counter = 0
		test_instances = []

	assert(len(test_gold_bio) == len(generated_texts))
	for p_txt, gold_bio, sl in zip(generated_texts, test_gold_bio, test_slots):
		pred_bio = marked_utterance_to_bio(p_txt)
		# it can happen that a generated sequence contains more (less) tokens than the original one,
		# we trancate / pad it in such cases
		if len(pred_bio) > len(gold_bio):
			pred_bio = pred_bio[:len(gold_bio)]
		else:
			pred_bio += ["O"]*(len(gold_bio)-len(pred_bio))
		test_pred_bio.append(pred_bio)

	# evaluate
	true_labels = flatten(test_gold_bio)
	predicted_labels = flatten(test_pred_bio)
	
	print(confusion_matrix(true_labels, predicted_labels))
	print("Micro f1:", f1_score(true_labels, predicted_labels, average="micro"))
	print("Macro f1:", f1_score(true_labels, predicted_labels, average="macro"))
	print("Weighted f1:", f1_score(true_labels, predicted_labels, average="weighted"))
	print()

	# calculate the scores for each slot type separately
	grouped = defaultdict(list)

	for k, p, g in zip(test_slots, test_pred_bio, test_gold_bio):
		grouped[k].append((p, g))

	for k, v in grouped.items():
		print("Slot:", k)
		p, g = zip(*v)
		true_labels = flatten(g)
		predicted_labels = flatten(p)
		print(confusion_matrix(true_labels, predicted_labels))
		print("Micro f1:", f1_score(true_labels, predicted_labels, average="micro"))
		print("Macro f1:", f1_score(true_labels, predicted_labels, average="macro"))
		print("Weighted f1:", f1_score(true_labels, predicted_labels, average="weighted"))
		print()


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument(
		"--model_name",
		default="Alibaba-NLP/gte-multilingual-base",
		help="Model to calculate embedding similarity.",
	)
	parser.add_argument(
		"--gen_model_name",
		default="Qwen/Qwen3-32B-FP8",
		#default="Qwen/Qwen3-14B",
		help="LLM to identify slots.",
	)
	parser.add_argument(
		"--data_path",
		default="./neg_samples_csv/",
		help="Path to the data.",
	)
	
	args = parser.parse_args()

	model_name = args.model_name
	gen_model_name = args.gen_model_name
	data_path = args.data_path

	data_dict = read_data(data_path)
	identify_slots(model_name, gen_model_name, data_dict)